compilation:
  cloud_properties:
    name: random
  network: logsearch_for_cloudfoundry1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 18bb4e2a-1ab6-49ab-ab7a-ea1e4da3854d
jobs:
- instances: 1
  name: ingestor_cloudfoundry
  networks:
  - name: logsearch_for_cloudfoundry1
    static_ips:
    - 10.244.200.2
  persistent_disk: 0
  release: logsearch-for-cloudfoundry
  resource_pool: small_z1
  templates:
  - name: ingestor_cloudfoundry-firehose
- instances: 1
  lifecycle: errand
  name: push-kibana
  networks:
  - name: logsearch_for_cloudfoundry1
  persistent_disk: 0
  resource_pool: small_z1
  templates:
  - name: push-kibana
    release: logsearch-for-cloudfoundry
meta:
  environment: logsearch-for-cloudfoundry-warden
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
name: logsearch-for-cloudfoundry-warden
networks:
- name: logsearch_for_cloudfoundry1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.200.0/30
    reserved:
    - 10.244.200.1
    static:
    - 10.244.200.2
  - cloud_properties:
      name: random
    range: 10.244.200.4/30
    reserved:
    - 10.244.200.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.8/30
    reserved:
    - 10.244.200.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.12/30
    reserved:
    - 10.244.200.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.16/30
    reserved:
    - 10.244.200.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.20/30
    reserved:
    - 10.244.200.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.24/30
    reserved:
    - 10.244.200.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.28/30
    reserved:
    - 10.244.200.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.32/30
    reserved:
    - 10.244.200.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.200.36/30
    reserved:
    - 10.244.200.37
    static: []
properties:
  cloudfoundry:
    admin_client_secret: admin-secret
    admin_password: admin
    admin_username: admin
    apps_domain: bonzofenix.dev
    cloudControllerUri: https://api.bonzofenix.dev
    firehose_password: admin
    firehose_user: admin
    skip_ssl_validation: true
    system_domain: bonzofenix.dev
    uaaUri: https://uaa.bonzofenix.dev
  elasticsearch:
    admin_ip: 10.244.10.2
    admin_port: 9200
  ingestor_cloudfoundry-firehose:
    debug: false
  push-kibana:
    app_name: logs
    oauth2_client_secret: kibana-oauth2-secret
  redis:
    host: 10.244.10.10
releases:
- name: logsearch-for-cloudfoundry
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: logsearch_for_cloudfoundry1
  size: 2
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

